[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.4.2
    tzapu/WiFiManager @ ^2.0.17
build_flags = -Wall -Wextra

