#include "mqtt_service.h"
#include <ArduinoJson.h>
#include <Preferences.h>
#include <PubSubClient.h>
#include <WiFi.h>
#include "alarm_service.h"
#include "config.h"
#include "network_settings.h"
namespace{WiFiClient net;PubSubClient mqtt(net);Preferences pref;MqttService*self=nullptr;void cb(char*t,byte*p,unsigned int n){if(self)self->handleMessage(t,p,n);}bool payload(byte*p,unsigned int n,char*out,size_t cap){if(!n||n>=cap)return false;memcpy(out,p,n);out[n]=0;return true;}}
void MqttService::begin(SystemState*s,AlarmService*a){state_=s;alarm_=a;self=this;pref.begin("air-config",false);threshold_=pref.getUShort("mq2ao",Config::MQ2_DEFAULT_THRESHOLD);if(!threshold_||threshold_>4095)threshold_=Config::MQ2_DEFAULT_THRESHOLD;tempHigh_=pref.getFloat("tempHi",Config::TEMP_HIGH_DEFAULT);humHigh_=pref.getFloat("humHi",Config::HUM_HIGH_DEFAULT);humLow_=pref.getFloat("humLo",Config::HUM_LOW_DEFAULT);mqtt.setServer(NetworkSettings::mqttHost(),NetworkSettings::mqttPort());mqtt.setCallback(cb);mqtt.setBufferSize(512);mqtt.setSocketTimeout(1);Serial.printf("[MQTT] AO threshold=%u\n",threshold_);}
void MqttService::connect(uint32_t now){if(now-lastAttempt_<Config::MQTT_RETRY_MS)return;lastAttempt_=now;mqtt.setServer(NetworkSettings::mqttHost(),NetworkSettings::mqttPort());char id[40];snprintf(id,sizeof(id),"%s-%06llX",Config::DEVICE_ID,(unsigned long long)(ESP.getEfuseMac()&0xffffff));if(mqtt.connect(id,NetworkSettings::mqttUsername(),NetworkSettings::mqttPassword(),"air/status",1,true,"OFFLINE")){Serial.println("[MQTT] Connected");mqtt.publish("air/status","ONLINE",true);subscribe();}else Serial.printf("[MQTT] Connect failed rc=%d\n",mqtt.state());}
void MqttService::subscribe(){mqtt.subscribe("air/config/mq2_ao_threshold");mqtt.subscribe("air/config/temp_high");mqtt.subscribe("air/config/humidity_high");mqtt.subscribe("air/config/humidity_low");mqtt.subscribe("air/command/buzzer");mqtt.subscribe("air/command/status");}
void MqttService::loop(uint32_t now){if(WiFi.status()!=WL_CONNECTED){state_->mqttOk=false;return;}if(!mqtt.connected())connect(now);if(!mqtt.connected()){state_->mqttOk=false;return;}mqtt.loop();state_->mqttOk=true;if(now-lastTelemetry_>=Config::TELEMETRY_MS){lastTelemetry_=now;publishTelemetry(now);}}
void MqttService::publishTelemetry(uint32_t now){if(!mqtt.connected())return;JsonDocument d;d["device_id"]=Config::DEVICE_ID;if(state_->shtOk){d["temperature"]=roundf(state_->temperature*10)/10;d["humidity"]=roundf(state_->humidity*10)/10;}else{d["temperature"]=nullptr;d["humidity"]=nullptr;}d["mq2_mode"]="AO";d["mq2_digital"]=state_->mq2Detected;d["mq2_raw"]=state_->mq2Raw;d["mq2_mv"]=state_->mq2Millivolts;d["mq2_threshold"]=state_->mq2EffectiveThreshold;d["mq2_ready"]=state_->mq2Ready;d["alarm"]=state_->alarm==AlarmState::ALARM;d["alarm_type"]=state_->alarm==AlarmState::ALARM?"MQ2_HIGH":"NONE";d["uptime_ms"]=now;char b[384];size_t n=serializeJson(d,b,sizeof(b));mqtt.publish("air/sensor/data",(uint8_t*)b,n,false);}
void MqttService::publishAlarmTransition(bool active,uint16_t v,uint16_t threshold){if(!mqtt.connected())return;JsonDocument d;d["type"]=active?"MQ2_HIGH":"MQ2_NORMAL";d["value"]=v;d["threshold"]=threshold;char b[128];size_t n=serializeJson(d,b,sizeof(b));mqtt.publish("air/alarm",(uint8_t*)b,n,false);}
void MqttService::handleMessage(char*t,uint8_t*p,unsigned int n){char s[32];if(!payload(p,n,s,sizeof(s)))return;if(!strcmp(t,"air/config/mq2_ao_threshold")){char*e;long v=strtol(s,&e,10);if(e!=s&&!*e&&v>=1&&v<=4095&&v!=threshold_){threshold_=v;pref.putUShort("mq2ao",threshold_);Serial.printf("[MQTT] AO threshold=%u\n",threshold_);}return;}if(!strcmp(t,"air/command/buzzer")){if(!strcmp(s,"AUTO"))alarm_->setBuzzerCommand(BuzzerMode::AUTO,millis());else if(!strcmp(s,"ON"))alarm_->setBuzzerCommand(BuzzerMode::ON,millis());else if(!strcmp(s,"OFF"))alarm_->setBuzzerCommand(BuzzerMode::MUTED,millis());}else if(!strcmp(t,"air/command/status")&&!strcmp(s,"GET")){mqtt.publish("air/status","ONLINE",true);publishTelemetry(millis());}else{char*e;float v=strtof(s,&e);if(e==s||*e||!isfinite(v))return;if(!strcmp(t,"air/config/temp_high")&&v>=-20&&v<=100&&v!=tempHigh_){tempHigh_=v;pref.putFloat("tempHi",v);}else if(!strcmp(t,"air/config/humidity_high")&&v>=0&&v<=100&&v!=humHigh_){humHigh_=v;pref.putFloat("humHi",v);}else if(!strcmp(t,"air/config/humidity_low")&&v>=0&&v<=100&&v!=humLow_){humLow_=v;pref.putFloat("humLo",v);}}}
