#include "network_settings.h"
#include <Preferences.h>
#include <WiFi.h>
#include <WiFiManager.h>
#include "secrets.h"
namespace{Preferences p;WiFiManager wm;char host[64]="192.168.137.227",port[6]="1883",user[40]=MQTT_USERNAME,pass[80]=MQTT_PASSWORD;WiFiManagerParameter ph("mqtt_host","MQTT broker",host,sizeof(host)),pp("mqtt_port","MQTT port",port,sizeof(port)),pu("mqtt_user","MQTT username",user,sizeof(user)),pw("mqtt_password","MQTT password",pass,sizeof(pass),"type='password'");void save(){strlcpy(host,ph.getValue(),sizeof(host));strlcpy(port,pp.getValue(),sizeof(port));strlcpy(user,pu.getValue(),sizeof(user));strlcpy(pass,pw.getValue(),sizeof(pass));long n=strtol(port,nullptr,10);if(host[0]&&n>0&&n<65536){p.putString("host",host);p.putUShort("port",n);p.putString("user",user);p.putString("pass",pass);}}}
void NetworkSettings::begin(){p.begin("network",false);String h=p.getString("host","192.168.137.227"),u=p.getString("user",MQTT_USERNAME),x=p.getString("pass",MQTT_PASSWORD);uint16_t n=p.getUShort("port",1883);strlcpy(host,h.c_str(),sizeof(host));snprintf(port,sizeof(port),"%u",n);strlcpy(user,u.c_str(),sizeof(user));strlcpy(pass,x.c_str(),sizeof(pass));ph.setValue(host,sizeof(host));pp.setValue(port,sizeof(port));pu.setValue(user,sizeof(user));pw.setValue(pass,sizeof(pass));wm.addParameter(&ph);wm.addParameter(&pp);wm.addParameter(&pu);wm.addParameter(&pw);wm.setSaveParamsCallback(save);wm.setConfigPortalBlocking(false);wm.setAPStaticIPConfig(IPAddress(192,168,4,1),IPAddress(192,168,4,1),IPAddress(255,255,255,0));wm.setConnectTimeout(10);wm.preloadWiFi(WIFI_SSID,WIFI_PASSWORD);if(wm.autoConnect("AIR_MONITOR_SETUP")){Serial.printf("[WIFI] Connected to %s\n",WiFi.SSID().c_str());Serial.printf("[WIFI] IP: %s\n",WiFi.localIP().toString().c_str());}else Serial.println("[WIFI] Portal AIR_MONITOR_SETUP http://192.168.4.1");}
void NetworkSettings::process(){wm.process();}const char*NetworkSettings::mqttHost(){return host;}uint16_t NetworkSettings::mqttPort(){return strtol(port,nullptr,10);}const char*NetworkSettings::mqttUsername(){return user;}const char*NetworkSettings::mqttPassword(){return pass;}

