#include "users_page.h"
#include "auth_service.h"
#include <QCheckBox>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFormLayout>
#include <QHeaderView>
#include <QInputDialog>
#include <QLineEdit>
#include <QMessageBox>
#include <QPushButton>
#include <QTableWidget>
#include <QVBoxLayout>

UsersPage::UsersPage(AuthService&a,const UserSession&s,QWidget*p):QWidget(p),auth_(a),session_(s){table_=new QTableWidget;table_->setColumnCount(5);table_->setHorizontalHeaderLabels({QStringLiteral("ID"),QStringLiteral("Tên đăng nhập"),QStringLiteral("Họ tên"),QStringLiteral("Vai trò"),QStringLiteral("Trạng thái")});table_->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);table_->setSelectionBehavior(QAbstractItemView::SelectRows);table_->setEditTriggers(QAbstractItemView::NoEditTriggers);table_->setAlternatingRowColors(true);table_->verticalHeader()->setVisible(false);auto*addButton=new QPushButton(QStringLiteral("Thêm tài khoản"));auto*editButton=new QPushButton(QStringLiteral("Sửa / Khóa"));auto*passwordButton=new QPushButton(QStringLiteral("Đổi mật khẩu"));auto*refreshButton=new QPushButton(QStringLiteral("Làm mới"));auto*bar=new QHBoxLayout;bar->addWidget(addButton);bar->addWidget(editButton);bar->addWidget(passwordButton);bar->addStretch();bar->addWidget(refreshButton);auto*l=new QVBoxLayout(this);l->setContentsMargins(20,20,20,20);l->setSpacing(12);l->addLayout(bar);l->addWidget(table_);connect(addButton,&QPushButton::clicked,this,&UsersPage::add);connect(editButton,&QPushButton::clicked,this,&UsersPage::edit);connect(passwordButton,&QPushButton::clicked,this,&UsersPage::changePassword);connect(refreshButton,&QPushButton::clicked,this,&UsersPage::refresh);setEnabled(session_.isAdmin());refresh();}
int UsersPage::selectedId()const{auto items=table_->selectedItems();return items.isEmpty()?0:table_->item(items.first()->row(),0)->text().toInt();}
void UsersPage::refresh(){QString e;auto rows=auth_.users(&e);table_->setRowCount(rows.size());for(int i=0;i<rows.size();++i){QStringList v={QString::number(rows[i].id),rows[i].username,rows[i].fullName,rows[i].role,rows[i].enabled?QStringLiteral("Có"):QStringLiteral("Khóa")};for(int c=0;c<v.size();++c)table_->setItem(i,c,new QTableWidgetItem(v[c]));}if(!e.isEmpty())QMessageBox::warning(this,QStringLiteral("Tài khoản"),e);}
void UsersPage::add(){if(!session_.isAdmin())return;QDialog d(this);d.setWindowTitle(QStringLiteral("Thêm tài khoản"));QLineEdit u,n,p;p.setEchoMode(QLineEdit::Password);QComboBox role;role.addItems({QStringLiteral("USER"),QStringLiteral("ADMIN")});QFormLayout f(&d);f.addRow(QStringLiteral("Username"),&u);f.addRow(QStringLiteral("Họ tên"),&n);f.addRow(QStringLiteral("Password"),&p);f.addRow(QStringLiteral("Role"),&role);QDialogButtonBox b(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);f.addRow(&b);connect(&b,&QDialogButtonBox::accepted,&d,&QDialog::accept);connect(&b,&QDialogButtonBox::rejected,&d,&QDialog::reject);if(d.exec()!=QDialog::Accepted)return;QString e;if(!auth_.addUser(session_,u.text(),p.text(),n.text(),role.currentText(),&e))QMessageBox::warning(this,QStringLiteral("Tài khoản"),e);else refresh();}
void UsersPage::edit(){int id=selectedId();if(!id)return;auto items=table_->selectedItems();int row=items.first()->row();QDialog d(this);d.setWindowTitle(QStringLiteral("Sửa tài khoản"));QLineEdit n(table_->item(row,2)->text());QComboBox role;role.addItems({QStringLiteral("USER"),QStringLiteral("ADMIN")});role.setCurrentText(table_->item(row,3)->text());QCheckBox enabled(QStringLiteral("Cho phép đăng nhập"));enabled.setChecked(table_->item(row,4)->text()==QStringLiteral("Có"));QFormLayout f(&d);f.addRow(QStringLiteral("Họ tên"),&n);f.addRow(QStringLiteral("Role"),&role);f.addRow(&enabled);QDialogButtonBox b(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);f.addRow(&b);connect(&b,&QDialogButtonBox::accepted,&d,&QDialog::accept);connect(&b,&QDialogButtonBox::rejected,&d,&QDialog::reject);if(d.exec()!=QDialog::Accepted)return;QString e;if(!auth_.updateUser(session_,id,n.text(),role.currentText(),enabled.isChecked(),&e))QMessageBox::warning(this,QStringLiteral("Tài khoản"),e);else refresh();}
void UsersPage::changePassword(){int id=selectedId();if(!id)return;bool ok=false;QString p=QInputDialog::getText(this,QStringLiteral("Đổi mật khẩu"),QStringLiteral("Mật khẩu mới"),QLineEdit::Password,{},&ok);if(!ok)return;QString e;if(!auth_.changePassword(session_,id,p,&e))QMessageBox::warning(this,QStringLiteral("Mật khẩu"),e);else QMessageBox::information(this,QStringLiteral("Mật khẩu"),QStringLiteral("Đã đổi mật khẩu."));}
